basePath: /api/v1
definitions:
  models.CreateSectionInput:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  models.Section:
    properties:
      created_at:
        type: string
      id:
        type: integer
      sort_order:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.UpdateSectionInput:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  models.UserLoginInput:
    properties:
      email:
        example: w@w.com
        type: string
      password:
        example: "123456"
        type: string
    type: object
  models.UserRegisterInput:
    properties:
      email:
        example: w@w.com
        type: string
      password:
        example: "123456"
        type: string
      username:
        example: walter
        type: string
    type: object
host: localhost:8088
info:
  contact: {}
  description: 使用 JWT 的簡易用戶驗證 API
  title: Micro Backend API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 輸入 email 與密碼後登入並取得 JWT Token
      parameters:
      - description: 登入資訊
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 使用者登入
      tags:
      - Auth
  /plans/sections:
    get:
      description: 依照排序列出所有區塊
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Section'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 取得所有區塊（Section）
      tags:
      - Plans
    post:
      consumes:
      - application/json
      description: 建立一個新的區塊（自動補上 sort_order）
      parameters:
      - description: 區塊資料
        in: body
        name: section
        required: true
        schema:
          $ref: '#/definitions/models.CreateSectionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 建立新區塊（Section）
      tags:
      - Plans
  /plans/sections/{id}:
    delete:
      description: 根據 ID 刪除一個區塊，並重新排序其他區塊
      parameters:
      - description: Section ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 刪除區塊（Section）
      tags:
      - Plans
    put:
      consumes:
      - application/json
      description: 根據 ID 修改區塊的標題
      parameters:
      - description: Section ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新資料
        in: body
        name: section
        required: true
        schema:
          $ref: '#/definitions/models.UpdateSectionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 更新區塊（Section 標題）
      tags:
      - Plans
  /profile:
    get:
      description: 使用 JWT 取得當前登入者資訊
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 取得個人資訊
      tags:
      - user
  /register:
    post:
      consumes:
      - application/json
      description: 使用者註冊帳號
      parameters:
      - description: 使用者資料
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 註冊使用者
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
